cc_library(
        name = "dpastar",
        hdrs = ["dpastar.hpp"],
        srcs = ["dpastar.cpp"],
        deps = ["//lib:cpp"],
        visibility = ["//visibility:public"],
        include_prefix = "roadef2018/ub_dpastar/",
)

