cc_library(
        name = "libdfs",
        hdrs = ["dfs.hpp"],
        srcs = ["dfs.cpp"],
        deps = ["//lib:cpp"],
        visibility = ["//visibility:public"],
        include_prefix = "roadef2018/ub_dfs/",
)

