cc_library(
        name = "libastar",
        hdrs = ["astar.hpp"],
        srcs = ["astar.cpp"],
        deps = ["//lib:cpp"],
        visibility = ["//visibility:public"],
        include_prefix = "roadef2018/ub_astar/",
)

