cc_library(
        name = "mbastar",
        hdrs = ["mbastar.hpp"],
        srcs = ["mbastar.cpp"],
        deps = ["//lib:cpp"],
        visibility = ["//visibility:public"],
        include_prefix = "roadef2018/ub_mbastar/",
)

